# fly.toml app configuration file generated for teams-app-fizanto on 2025-05-09T17:46:32+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teams-app-fizanto'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "fizanto_data"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
